export const appPaths = {
  login: "/auth/login",
  signUp: "/auth/signup",
  forgotPassword: "/auth/forgot-password",
  unauthorized: "/unauthorized",
  dashboard: "/dashboard",
  academicStructure: "/academic-structure",
  program: "/program",
  courses: "/courses",
  settings: "/settings",
  staff: "/staff",
  students: "/students",
  roleSelection: "/role-selection",
  courseRegistration: "/course-registration",
  gradingConfig: "/grading-config",
  admissionConfig: "/admission-config",
  admissionCandidates: "/admission-candidates",
  assessment: "/assessment",
  // Add other app paths here
};
