export const appPaths = {
  login: "/auth/login",
  signUp: "/auth/signup",
  candidateSignUp: "/auth/candidate-signup",
  forgotPassword: "/auth/forgot-password",
  resetPassword: "/auth/reset-password/:token",
  unauthorized: "/unauthorized",
  dashboard: "/dashboard",
  academicStructure: "/academic-structure",
  program: "/program",
  courses: "/courses",
  settings: "/settings",
  staff: "/staff",
  students: "/students",
  roleSelection: "/role-selection",
  courseRegistration: "/course-registration",
  gradingConfig: "/grading-config",
  admissionConfig: "/admission-config",
  admissionCandidates: "/admission-candidates",
  assessment: "/assessment",
  resultBroadsheet: "/results/broadsheet",
  studentTransitions: "/student-transitions",
  billing: "/billing",

  // Student Module Paths
  studentHome: "/student",
  StudentInvoices: "/invoices",
  studentInvoicePay: "/invoices/:invoiceId",
  StudentPayments: "/payments",
  studentPaymentReceipt: "/payments/:paymentId",
  StudentResults: "/results",
  StudentBioData: "/bio-data",
  profile: "/profile",
  StudentApply: "/apply",
  StudentApplication: "/application",
  StudentApplicationAcknowledgement: "/application/acknowledgement",
  StudentAdmission: "/admission",

  // Add other app paths here
};
