export const Permission = {
  // Faculties
  FacultiesList: "faculties:list",
  FacultiesRead: "faculties:read",
  FacultiesCreate: "faculties:create",
  FacultiesUpdate: "faculties:update",
  FacultiesDelete: "faculties:delete",
  FacultiesManage: "faculties:manage",

  // Departments
  DepartmentsList: "departments:list",
  DepartmentsRead: "departments:read",
  DepartmentsCreate: "departments:create",
  DepartmentsUpdate: "departments:update",
  DepartmentsDelete: "departments:delete",
  DepartmentsManage: "departments:manage",

  // Programs
  ProgramsList: "programs:list",
  ProgramsRead: "programs:read",
  ProgramsCreate: "programs:create",
  ProgramsUpdate: "programs:update",
  ProgramsDelete: "programs:delete",
  ProgramsManage: "programs:manage",

  // Courses
  CoursesList: "courses:list",
  CoursesRead: "courses:read",
  CoursesCreate: "courses:create",
  CoursesUpdate: "courses:update",
  CoursesDelete: "courses:delete",
  CoursesManage: "courses:manage",

  // Course Configurations
  CourseConfigurationsList: "course-configurations:list",
  CourseConfigurationsRead: "course-configurations:read",
  CourseConfigurationsCreate: "course-configurations:create",
  CourseConfigurationsUpdate: "course-configurations:update",
  CourseConfigurationsDelete: "course-configurations:delete",
  CourseConfigurationsManage: "course-configurations:manage",
  CourseConfigsList: "course-configurations:list",
  CourseConfigsRead: "course-configurations:read",
  CourseConfigsCreate: "course-configurations:create",
  CourseConfigsUpdate: "course-configurations:update",
  CourseConfigsDelete: "course-configurations:delete",
  CourseConfigsManage: "course-configurations:manage",
  CourseAssessmentPoliciesList: "course-configurations:list",
  CourseAssessmentPoliciesRead: "course-configurations:read",
  CourseAssessmentPoliciesCreate: "course-configurations:create",
  CourseAssessmentPoliciesUpdate: "course-configurations:update",
  CourseAssessmentPoliciesDelete: "course-configurations:delete",
  CourseAssessmentComponentsList: "course-configurations:list",
  CourseAssessmentComponentsCreate: "course-configurations:create",
  CourseAssessmentComponentsUpdate: "course-configurations:update",
  CourseAssessmentComponentsDelete: "course-configurations:delete",

  // Curriculum Versions
  CurriculumVersionsList: "curriculum-versions:list",
  CurriculumVersionsRead: "curriculum-versions:read",
  CurriculumVersionsCreate: "curriculum-versions:create",
  CurriculumVersionsUpdate: "curriculum-versions:update",
  CurriculumVersionsDelete: "curriculum-versions:delete",
  CurriculumVersionsManage: "curriculum-versions:manage",

  // Academic Sessions
  AcademicSessionsList: "academic-sessions:list",
  AcademicSessionsRead: "academic-sessions:read",
  AcademicSessionsCreate: "academic-sessions:create",
  AcademicSessionsUpdate: "academic-sessions:update",
  AcademicSessionsDelete: "academic-sessions:delete",
  AcademicSessionsManage: "academic-sessions:manage",

  // Semesters
  SemestersList: "semesters:list",
  SemestersRead: "semesters:read",
  SemestersCreate: "semesters:create",
  SemestersUpdate: "semesters:update",
  SemestersDelete: "semesters:delete",
  SemestersManage: "semesters:manage",

  // Semester Types
  SemesterTypesList: "semester-types:list",
  SemesterTypesRead: "semester-types:read",
  SemesterTypesCreate: "semester-types:create",
  SemesterTypesUpdate: "semester-types:update",
  SemesterTypesDelete: "semester-types:delete",
  SemesterTypesManage: "semester-types:manage",

  // Levels
  LevelsList: "levels:list",
  LevelsRead: "levels:read",
  LevelsCreate: "levels:create",
  LevelsUpdate: "levels:update",
  LevelsDelete: "levels:delete",
  LevelsManage: "levels:manage",

  // Students
  StudentsList: "students:list",
  StudentsRead: "students:read",
  StudentsCreate: "students:create",
  StudentsUpdate: "students:update",
  StudentsDelete: "students:delete",
  StudentsManage: "students:manage",

  // Student Enrollment Transitions
  StudentEnrollmentTransitionsList: "student-enrollment-transitions:list",
  StudentEnrollmentTransitionsRead: "student-enrollment-transitions:read",
  StudentEnrollmentTransitionsCreate: "student-enrollment-transitions:create",
  StudentEnrollmentTransitionsUpdate: "student-enrollment-transitions:update",
  StudentEnrollmentTransitionsDelete: "student-enrollment-transitions:delete",
  StudentEnrollmentTransitionsManage: "student-enrollment-transitions:manage",

  // Student Course Registrations
  StudentCourseRegistrationsList: "student-course-registrations:list",
  StudentCourseRegistrationsRead: "student-course-registrations:read",
  StudentCourseRegistrationsCreate: "student-course-registrations:create",
  StudentCourseRegistrationsUpdate: "student-course-registrations:update",
  StudentCourseRegistrationsDelete: "student-course-registrations:delete",
  StudentCourseRegistrationsManage: "student-course-registrations:manage",

  // Student Score Sheets
  StudentScoreSheetsList: "student-score-sheets:list",
  StudentScoreSheetsRead: "student-score-sheets:read",
  StudentScoreSheetsCreate: "student-score-sheets:create",
  StudentScoreSheetsUpdate: "student-score-sheets:update",
  StudentScoreSheetsDelete: "student-score-sheets:delete",
  StudentScoreSheetsManage: "student-score-sheets:manage",
  StudentScoreSheetList: "student-score-sheet:list",
  StudentScoreSheetRead: "student-score-sheet:read",
  StudentScoreSheetCreate: "student-score-sheet:create",
  StudentScoreSheetUpdate: "student-score-sheet:update",
  StudentScoreSheetDelete: "student-score-sheet:delete",
  StudentScoreSheetManage: "student-score-sheet:manage",

  // Student Transition Statuses
  StudentTransitionStatusesList: "student-transition-statuses:list",
  StudentTransitionStatusesRead: "student-transition-statuses:read",
  StudentTransitionStatusesCreate: "student-transition-statuses:create",
  StudentTransitionStatusesUpdate: "student-transition-statuses:update",
  StudentTransitionStatusesDelete: "student-transition-statuses:delete",
  StudentTransitionStatusesManage: "student-transition-statuses:manage",

  // Roles
  RolesList: "roles:list",
  RolesRead: "roles:read",
  RolesCreate: "roles:create",
  RolesUpdate: "roles:update",
  RolesDelete: "roles:delete",
  RolesManage: "roles:manage",

  // Permissions
  PermissionsList: "permissions:list",
  PermissionsRead: "permissions:read",
  PermissionsCreate: "permissions:create",
  PermissionsUpdate: "permissions:update",
  PermissionsDelete: "permissions:delete",
  PermissionsManage: "permissions:manage",

  // User Roles
  UserRolesList: "user-roles:list",
  UserRolesRead: "user-roles:read",
  UserRolesCreate: "user-roles:create",
  UserRolesUpdate: "user-roles:update",
  UserRolesDelete: "user-roles:delete",
  UserRolesManage: "user-roles:manage",

  // System Configs
  SystemConfigsList: "system-configs:list",
  SystemConfigsRead: "system-configs:read",
  SystemConfigsCreate: "system-configs:create",
  SystemConfigsUpdate: "system-configs:update",
  SystemConfigsDelete: "system-configs:delete",
  SystemConfigsManage: "system-configs:manage",

  // Brand Configs
  BrandConfigsList: "brand-configs:list",
  BrandConfigsRead: "brand-configs:read",
  BrandConfigsCreate: "brand-configs:create",
  BrandConfigsUpdate: "brand-configs:update",
  BrandConfigsDelete: "brand-configs:delete",
  BrandConfigsManage: "brand-configs:manage",

  // Grading Schema Configs
  GradingSchemaConfigsList: "grading-schema-configs:list",
  GradingSchemaConfigsRead: "grading-schema-configs:read",
  GradingSchemaConfigsCreate: "grading-schema-configs:create",
  GradingSchemaConfigsUpdate: "grading-schema-configs:update",
  GradingSchemaConfigsDelete: "grading-schema-configs:delete",
  GradingSchemaConfigsManage: "grading-schema-configs:manage",

  // Grading
  GradingList: "grading:list",
  GradingRead: "grading:read",
  GradingCreate: "grading:create",
  GradingUpdate: "grading:update",
  GradingDelete: "grading:delete",
  GradingManage: "grading:manage",
  ScoreEvaluationStatusesList: "grading:list",
  ScoreEvaluationStatusesCreate: "grading:create",
  ScoreEvaluationStatusesUpdate: "grading:update",
  ScoreEvaluationStatusesDelete: "grading:delete",

  // Graduation Requirements
  GraduationRequirementsList: "graduation-requirements:list",
  GraduationRequirementsRead: "graduation-requirements:read",
  GraduationRequirementsCreate: "graduation-requirements:create",
  GraduationRequirementsUpdate: "graduation-requirements:update",
  GraduationRequirementsDelete: "graduation-requirements:delete",
  GraduationRequirementsManage: "graduation-requirements:manage",

  // Staff
  StaffList: "staff:list",
  StaffRead: "staff:read",
  StaffCreate: "staff:create",
  StaffUpdate: "staff:update",
  StaffDelete: "staff:delete",
  StaffManage: "staff:manage",

  // Profiles
  ProfilesList: "profiles:list",
  ProfilesRead: "profiles:read",
  ProfilesCreate: "profiles:create",
  ProfilesUpdate: "profiles:update",
  ProfilesDelete: "profiles:delete",
  ProfilesManage: "profiles:manage",

  // System Time Frames
  SystemTimeFramesList: "system-time-frames:list",
  SystemTimeFramesRead: "system-time-frames:read",
  SystemTimeFramesCreate: "system-time-frames:create",
  SystemTimeFramesUpdate: "system-time-frames:update",
  SystemTimeFramesDelete: "system-time-frames:delete",
  SystemTimeFramesManage: "system-time-frames:manage",

  // Registration Credit Limits
  RegistrationCreditLimitsList: "registration-credit-limits:list",
  RegistrationCreditLimitsRead: "registration-credit-limits:read",
  RegistrationCreditLimitsCreate: "registration-credit-limits:create",
  RegistrationCreditLimitsUpdate: "registration-credit-limits:update",
  RegistrationCreditLimitsDelete: "registration-credit-limits:delete",
  RegistrationCreditLimitsManage: "registration-credit-limits:manage",

  // Bulk Uploads & Transitions
  BulkCourseUploadsList: "bulk-course-uploads:list",
  BulkCourseUploadsRead: "bulk-course-uploads:read",
  BulkCourseUploadsCreate: "bulk-course-uploads:create",
  BulkCourseUploadsUpdate: "bulk-course-uploads:update",
  BulkCourseUploadsDelete: "bulk-course-uploads:delete",
  BulkCourseUploadsManage: "bulk-course-uploads:manage",

  BulkStudentUploadsList: "bulk-student-uploads:list",
  BulkStudentUploadsRead: "bulk-student-uploads:read",
  BulkStudentUploadsCreate: "bulk-student-uploads:create",
  BulkStudentUploadsUpdate: "bulk-student-uploads:update",
  BulkStudentUploadsDelete: "bulk-student-uploads:delete",
  BulkStudentUploadsManage: "bulk-student-uploads:manage",

  BulkEnrollmentTransitionsList: "bulk-enrollment-transitions:list",
  BulkEnrollmentTransitionsRead: "bulk-enrollment-transitions:read",
  BulkEnrollmentTransitionsCreate: "bulk-enrollment-transitions:create",
  BulkEnrollmentTransitionsUpdate: "bulk-enrollment-transitions:update",
  BulkEnrollmentTransitionsDelete: "bulk-enrollment-transitions:delete",
  BulkEnrollmentTransitionsManage: "bulk-enrollment-transitions:manage",

  CourseRegistrationFactoryList: "course-registration-factory:list",
  CourseRegistrationFactoryRead: "course-registration-factory:read",
  CourseRegistrationFactoryCreate: "course-registration-factory:create",
  CourseRegistrationFactoryUpdate: "course-registration-factory:update",
  CourseRegistrationFactoryDelete: "course-registration-factory:delete",
  CourseRegistrationFactoryManage: "course-registration-factory:manage",

  // States & LGAs
  StatesList: "states:list",
  StatesRead: "states:read",
  StatesCreate: "states:create",
  StatesUpdate: "states:update",
  StatesDelete: "states:delete",
  StatesManage: "states:manage",

  LgasList: "lgas:list",
  LgasRead: "lgas:read",
  LgasCreate: "lgas:create",
  LgasUpdate: "lgas:update",
  LgasDelete: "lgas:delete",
  LgasManage: "lgas:manage",

  // Tenants & Permission Catalogue
  TenantsList: "tenants:list",
  TenantsRead: "tenants:read",
  TenantsCreate: "tenants:create",
  TenantsUpdate: "tenants:update",
  TenantsDelete: "tenants:delete",
  TenantsManage: "tenants:manage",

  PermissionCatalogueList: "permission-catalogue:list",
  PermissionCatalogueRead: "permission-catalogue:read",
  PermissionCatalogueCreate: "permission-catalogue:create",
  PermissionCatalogueUpdate: "permission-catalogue:update",
  PermissionCatalogueDelete: "permission-catalogue:delete",
  PermissionCatalogueManage: "permission-catalogue:manage",

  // Dynamic Forms
  DynamicFormsList: "dynamic-forms:list",
  DynamicFormsRead: "dynamic-forms:read",
  DynamicFormsCreate: "dynamic-forms:create",
  DynamicFormsUpdate: "dynamic-forms:update",
  DynamicFormsDelete: "dynamic-forms:delete",
  DynamicFormsManage: "dynamic-forms:manage",

  DynamicFormAssignmentsList: "dynamic-form-assignments:list",
  DynamicFormAssignmentsRead: "dynamic-form-assignments:read",
  DynamicFormAssignmentsCreate: "dynamic-form-assignments:create",
  DynamicFormAssignmentsUpdate: "dynamic-form-assignments:update",
  DynamicFormAssignmentsDelete: "dynamic-form-assignments:delete",
  DynamicFormAssignmentsManage: "dynamic-form-assignments:manage",

  DynamicFormSubmissionsList: "dynamic-form-submissions:list",
  DynamicFormSubmissionsRead: "dynamic-form-submissions:read",
  DynamicFormSubmissionsCreate: "dynamic-form-submissions:create",
  DynamicFormSubmissionsUpdate: "dynamic-form-submissions:update",
  DynamicFormSubmissionsDelete: "dynamic-form-submissions:delete",
  DynamicFormSubmissionsManage: "dynamic-form-submissions:manage",

  DynamicFormSectionsList: "dynamic-form-sections:list",
  DynamicFormSectionsRead: "dynamic-form-sections:read",
  DynamicFormSectionsCreate: "dynamic-form-sections:create",
  DynamicFormSectionsUpdate: "dynamic-form-sections:update",
  DynamicFormSectionsDelete: "dynamic-form-sections:delete",
  DynamicFormSectionsManage: "dynamic-form-sections:manage",

  DynamicFormFieldsList: "dynamic-form-fields:list",
  DynamicFormFieldsRead: "dynamic-form-fields:read",
  DynamicFormFieldsCreate: "dynamic-form-fields:create",
  DynamicFormFieldsUpdate: "dynamic-form-fields:update",
  DynamicFormFieldsDelete: "dynamic-form-fields:delete",
  DynamicFormFieldsManage: "dynamic-form-fields:manage",

  // Admissions
  AdmissionCyclesList: "admission-cycles:list",
  AdmissionCyclesRead: "admission-cycles:read",
  AdmissionCyclesCreate: "admission-cycles:create",
  AdmissionCyclesUpdate: "admission-cycles:update",
  AdmissionCyclesDelete: "admission-cycles:delete",
  AdmissionCyclesManage: "admission-cycles:manage",
  AdmissionCyclesTransition: "admission-cycles:manage",

  AdmissionCandidatesList: "admission-candidates:list",
  AdmissionCandidatesRead: "admission-candidates:read",
  AdmissionCandidatesCreate: "admission-candidates:create",
  AdmissionCandidatesUpdate: "admission-candidates:update",
  AdmissionCandidatesDelete: "admission-candidates:delete",
  AdmissionCandidatesManage: "admission-candidates:manage",

  AdmissionApplicationsList: "admission-applications:list",
  AdmissionApplicationsRead: "admission-applications:read",
  AdmissionApplicationsCreate: "admission-applications:create",
  AdmissionApplicationsUpdate: "admission-applications:update",
  AdmissionApplicationsDelete: "admission-applications:delete",
  AdmissionApplicationsManage: "admission-applications:manage",

  AdmissionScreeningsList: "admission-screenings:list",
  AdmissionScreeningsRead: "admission-screenings:read",
  AdmissionScreeningsCreate: "admission-screenings:create",
  AdmissionScreeningsUpdate: "admission-screenings:update",
  AdmissionScreeningsDelete: "admission-screenings:delete",
  AdmissionScreeningsManage: "admission-screenings:manage",

  AdmissionRecommendedCandidatesList: "admission-recommended-candidates:list",
  AdmissionRecommendedCandidatesRead: "admission-recommended-candidates:read",
  AdmissionRecommendedCandidatesCreate: "admission-recommended-candidates:create",
  AdmissionRecommendedCandidatesUpdate: "admission-recommended-candidates:update",
  AdmissionRecommendedCandidatesDelete: "admission-recommended-candidates:delete",
  AdmissionRecommendedCandidatesManage: "admission-recommended-candidates:manage",

  AdmissionCandidateOffersList: "admission-candidate-offers:list",
  AdmissionCandidateOffersRead: "admission-candidate-offers:read",
  AdmissionCandidateOffersCreate: "admission-candidate-offers:create",
  AdmissionCandidateOffersUpdate: "admission-candidate-offers:update",
  AdmissionCandidateOffersDelete: "admission-candidate-offers:delete",
  AdmissionCandidateOffersManage: "admission-candidate-offers:manage",

  AdmissionGeographyRulesList: "admission-geography-rules:list",
  AdmissionGeographyRulesRead: "admission-geography-rules:read",
  AdmissionGeographyRulesCreate: "admission-geography-rules:create",
  AdmissionGeographyRulesUpdate: "admission-geography-rules:update",
  AdmissionGeographyRulesDelete: "admission-geography-rules:delete",
  AdmissionGeographyRulesManage: "admission-geography-rules:manage",

  ProgramAdmissionConfigsList: "program-admission-configs:list",
  ProgramAdmissionConfigsRead: "program-admission-configs:read",
  ProgramAdmissionConfigsCreate: "program-admission-configs:create",
  ProgramAdmissionConfigsUpdate: "program-admission-configs:update",
  ProgramAdmissionConfigsDelete: "program-admission-configs:delete",
  ProgramAdmissionConfigsManage: "program-admission-configs:manage",
  AdmissionProgramAdmissionConfigsList: "program-admission-configs:list",
  AdmissionProgramAdmissionConfigsCreate: "program-admission-configs:create",
  AdmissionProgramAdmissionConfigsUpdate: "program-admission-configs:update",
  AdmissionProgramAdmissionConfigsDelete: "program-admission-configs:delete",
  AdmissionProgramAdmissionConfigsManage: "program-admission-configs:manage",

  ProgramOlevelRequirementsList: "program-olevel-requirements:list",
  ProgramOlevelRequirementsRead: "program-olevel-requirements:read",
  ProgramOlevelRequirementsCreate: "program-olevel-requirements:create",
  ProgramOlevelRequirementsUpdate: "program-olevel-requirements:update",
  ProgramOlevelRequirementsDelete: "program-olevel-requirements:delete",
  ProgramOlevelRequirementsManage: "program-olevel-requirements:manage",
  AdmissionProgramOlevelRulesList: "program-olevel-requirements:list",
  AdmissionProgramOlevelRulesCreate: "program-olevel-requirements:create",
  AdmissionProgramOlevelRulesUpdate: "program-olevel-requirements:update",
  AdmissionProgramOlevelRulesDelete: "program-olevel-requirements:delete",

  ProgramAlternativesList: "program-alternatives:list",
  ProgramAlternativesRead: "program-alternatives:read",
  ProgramAlternativesCreate: "program-alternatives:create",
  ProgramAlternativesUpdate: "program-alternatives:update",
  ProgramAlternativesDelete: "program-alternatives:delete",
  ProgramAlternativesManage: "program-alternatives:manage",

  OlevelSubjectsList: "olevel-subjects:list",
  OlevelSubjectsRead: "olevel-subjects:read",
  OlevelSubjectsCreate: "olevel-subjects:create",
  OlevelSubjectsUpdate: "olevel-subjects:update",
  OlevelSubjectsDelete: "olevel-subjects:delete",
  OlevelSubjectsManage: "olevel-subjects:manage",
  AdmissionOlevelSubjectsList: "olevel-subjects:list",
  AdmissionOlevelSubjectsCreate: "olevel-subjects:create",
  AdmissionOlevelSubjectsUpdate: "olevel-subjects:update",
  AdmissionOlevelSubjectsDelete: "olevel-subjects:delete",
  AdmissionOlevelSubjectsManage: "olevel-subjects:manage",

  OlevelGradePointsList: "olevel-grade-points:list",
  OlevelGradePointsRead: "olevel-grade-points:read",
  OlevelGradePointsCreate: "olevel-grade-points:create",
  OlevelGradePointsUpdate: "olevel-grade-points:update",
  OlevelGradePointsDelete: "olevel-grade-points:delete",
  OlevelGradePointsManage: "olevel-grade-points:manage",
  AdmissionOlevelGradePointsList: "olevel-grade-points:list",
  AdmissionOlevelGradePointsCreate: "olevel-grade-points:create",
  AdmissionOlevelGradePointsUpdate: "olevel-grade-points:update",
  AdmissionOlevelGradePointsDelete: "olevel-grade-points:delete",

  JambCombinationGroupsList: "jamb-combination-groups:list",
  JambCombinationGroupsRead: "jamb-combination-groups:read",
  JambCombinationGroupsCreate: "jamb-combination-groups:create",
  JambCombinationGroupsUpdate: "jamb-combination-groups:update",
  JambCombinationGroupsDelete: "jamb-combination-groups:delete",
  JambCombinationGroupsManage: "jamb-combination-groups:manage",
  AdmissionJambRulesList: "jamb-combination-groups:list",
  AdmissionJambRulesCreate: "jamb-combination-groups:create",
  AdmissionJambRulesUpdate: "jamb-combination-groups:update",
  AdmissionJambRulesDelete: "jamb-combination-groups:delete",
  AdmissionJambRulesManage: "jamb-combination-groups:manage",

  JambCombinationOptionsList: "jamb-combination-options:list",
  JambCombinationOptionsRead: "jamb-combination-options:read",
  JambCombinationOptionsCreate: "jamb-combination-options:create",
  JambCombinationOptionsUpdate: "jamb-combination-options:update",
  JambCombinationOptionsDelete: "jamb-combination-options:delete",
  JambCombinationOptionsManage: "jamb-combination-options:manage",

  JambSubjectCombinationsList: "jamb-subject-combinations:list",
  JambSubjectCombinationsRead: "jamb-subject-combinations:read",
  JambSubjectCombinationsCreate: "jamb-subject-combinations:create",
  JambSubjectCombinationsUpdate: "jamb-subject-combinations:update",
  JambSubjectCombinationsDelete: "jamb-subject-combinations:delete",
  JambSubjectCombinationsManage: "jamb-subject-combinations:manage",

  AdmissionDocumentTypesList: "admission-document-types:list",
  AdmissionDocumentTypesRead: "admission-document-types:read",
  AdmissionDocumentTypesCreate: "admission-document-types:create",
  AdmissionDocumentTypesUpdate: "admission-document-types:update",
  AdmissionDocumentTypesDelete: "admission-document-types:delete",
  AdmissionDocumentTypesManage: "admission-document-types:manage",

  AdmissionDocumentUploadsList: "admission-document-uploads:list",
  AdmissionDocumentUploadsRead: "admission-document-uploads:read",
  AdmissionDocumentUploadsCreate: "admission-document-uploads:create",
  AdmissionDocumentUploadsUpdate: "admission-document-uploads:update",
  AdmissionDocumentUploadsDelete: "admission-document-uploads:delete",
  AdmissionDocumentUploadsManage: "admission-document-uploads:manage",

  PriorQualificationTypesList: "prior-qualification-types:list",
  PriorQualificationTypesRead: "prior-qualification-types:read",
  PriorQualificationTypesCreate: "prior-qualification-types:create",
  PriorQualificationTypesUpdate: "prior-qualification-types:update",
  PriorQualificationTypesDelete: "prior-qualification-types:delete",
  PriorQualificationTypesManage: "prior-qualification-types:manage",
  AdmissionPriorQualificationTypesList: "prior-qualification-types:list",
  AdmissionPriorQualificationTypesCreate: "prior-qualification-types:create",
  AdmissionPriorQualificationTypesUpdate: "prior-qualification-types:update",
  AdmissionPriorQualificationTypesDelete: "prior-qualification-types:delete",

  ProgramPriorQualificationRequirementsList: "program-prior-qualification-requirements:list",
  ProgramPriorQualificationRequirementsRead: "program-prior-qualification-requirements:read",
  ProgramPriorQualificationRequirementsCreate: "program-prior-qualification-requirements:create",
  ProgramPriorQualificationRequirementsUpdate: "program-prior-qualification-requirements:update",
  ProgramPriorQualificationRequirementsDelete: "program-prior-qualification-requirements:delete",
  ProgramPriorQualificationRequirementsManage: "program-prior-qualification-requirements:manage",
  AdmissionProgramPriorQualificationRequirementsList: "program-prior-qualification-requirements:list",
  AdmissionProgramPriorQualificationRequirementsCreate: "program-prior-qualification-requirements:create",
  AdmissionProgramPriorQualificationRequirementsUpdate: "program-prior-qualification-requirements:update",
  AdmissionProgramPriorQualificationRequirementsDelete: "program-prior-qualification-requirements:delete",

  PostUtmeScoresList: "post-utme-scores:list",
  PostUtmeScoresRead: "post-utme-scores:read",
  PostUtmeScoresCreate: "post-utme-scores:create",
  PostUtmeScoresUpdate: "post-utme-scores:update",
  PostUtmeScoresDelete: "post-utme-scores:delete",
  PostUtmeScoresManage: "post-utme-scores:manage",
  AdmissionScoringStrategiesList: "post-utme-scores:list",
  AdmissionScoringStrategiesCreate: "post-utme-scores:create",
  AdmissionScoringStrategiesUpdate: "post-utme-scores:update",
  AdmissionScoringStrategiesDelete: "post-utme-scores:delete",
  AdmissionScoringStrategiesManage: "post-utme-scores:manage",

  // Student / Me Portal
  MeAdmissionCandidateList: "me-admission-candidate:list",
  MeAdmissionCandidateRead: "me-admission-candidate:read",
  MeAdmissionCandidateCreate: "me-admission-candidate:create",
  MeAdmissionCandidateUpdate: "me-admission-candidate:update",
  MeAdmissionCandidateDelete: "me-admission-candidate:delete",
  MeAdmissionCandidateManage: "me-admission-candidate:manage",

  MeAdmissionApplicationList: "me-admission-application:list",
  MeAdmissionApplicationRead: "me-admission-application:read",
  MeAdmissionApplicationCreate: "me-admission-application:create",
  MeAdmissionApplicationUpdate: "me-admission-application:update",
  MeAdmissionApplicationDelete: "me-admission-application:delete",
  MeAdmissionApplicationManage: "me-admission-application:manage",

  MeAdmissionProgressList: "me-admission-progress:list",
  MeAdmissionProgressRead: "me-admission-progress:read",
  MeAdmissionProgressCreate: "me-admission-progress:create",
  MeAdmissionProgressUpdate: "me-admission-progress:update",
  MeAdmissionProgressDelete: "me-admission-progress:delete",
  MeAdmissionProgressManage: "me-admission-progress:manage",

  MeBillingInvoicesList: "me-billing-invoices:list",
  MeBillingInvoicesRead: "me-billing-invoices:read",
  MeBillingInvoicesCreate: "me-billing-invoices:create",
  MeBillingInvoicesUpdate: "me-billing-invoices:update",
  MeBillingInvoicesDelete: "me-billing-invoices:delete",
  MeBillingInvoicesManage: "me-billing-invoices:manage",

  MeBillingPaymentsList: "me-billing-payments:list",
  MeBillingPaymentsRead: "me-billing-payments:read",
  MeBillingPaymentsCreate: "me-billing-payments:create",
  MeBillingPaymentsUpdate: "me-billing-payments:update",
  MeBillingPaymentsDelete: "me-billing-payments:delete",
  MeBillingPaymentsManage: "me-billing-payments:manage",

  MeBillingPaymentTransactionsList: "me-billing-payment-transactions:list",
  MeBillingPaymentTransactionsRead: "me-billing-payment-transactions:read",
  MeBillingPaymentTransactionsCreate: "me-billing-payment-transactions:create",
  MeBillingPaymentTransactionsUpdate: "me-billing-payment-transactions:update",
  MeBillingPaymentTransactionsDelete: "me-billing-payment-transactions:delete",
  MeBillingPaymentTransactionsManage: "me-billing-payment-transactions:manage",

  // Billing
  BillingBillableEventsList: "billing-billable-events:list",
  BillingBillableEventsRead: "billing-billable-events:read",
  BillingBillableEventsCreate: "billing-billable-events:create",
  BillingBillableEventsUpdate: "billing-billable-events:update",
  BillingBillableEventsDelete: "billing-billable-events:delete",
  BillingBillableEventsManage: "billing-billable-events:manage",

  BillingFeeItemsList: "billing-fee-items:list",
  BillingFeeItemsRead: "billing-fee-items:read",
  BillingFeeItemsCreate: "billing-fee-items:create",
  BillingFeeItemsUpdate: "billing-fee-items:update",
  BillingFeeItemsDelete: "billing-fee-items:delete",
  BillingFeeItemsManage: "billing-fee-items:manage",

  BillingFeeChargesList: "billing-fee-charges:list",
  BillingFeeChargesRead: "billing-fee-charges:read",
  BillingFeeChargesCreate: "billing-fee-charges:create",
  BillingFeeChargesUpdate: "billing-fee-charges:update",
  BillingFeeChargesDelete: "billing-fee-charges:delete",
  BillingFeeChargesManage: "billing-fee-charges:manage",

  BillingInvoicesList: "billing-invoices:list",
  BillingInvoicesRead: "billing-invoices:read",
  BillingInvoicesCreate: "billing-invoices:create",
  BillingInvoicesUpdate: "billing-invoices:update",
  BillingInvoicesDelete: "billing-invoices:delete",
  BillingInvoicesManage: "billing-invoices:manage",

  BillingPaymentsList: "billing-payments:list",
  BillingPaymentsRead: "billing-payments:read",
  BillingPaymentsCreate: "billing-payments:create",
  BillingPaymentsUpdate: "billing-payments:update",
  BillingPaymentsDelete: "billing-payments:delete",
  BillingPaymentsManage: "billing-payments:manage",

  BillingPaymentTransactionsList: "billing-payment-transactions:list",
  BillingPaymentTransactionsRead: "billing-payment-transactions:read",
  BillingPaymentTransactionsCreate: "billing-payment-transactions:create",
  BillingPaymentTransactionsUpdate: "billing-payment-transactions:update",
  BillingPaymentTransactionsDelete: "billing-payment-transactions:delete",
  BillingPaymentTransactionsManage: "billing-payment-transactions:manage",

  BillingPricingRulesList: "billing-pricing-rules:list",
  BillingPricingRulesRead: "billing-pricing-rules:read",
  BillingPricingRulesCreate: "billing-pricing-rules:create",
  BillingPricingRulesUpdate: "billing-pricing-rules:update",
  BillingPricingRulesDelete: "billing-pricing-rules:delete",
  BillingPricingRulesManage: "billing-pricing-rules:manage",

  BillingPricingRuleItemsList: "billing-pricing-rule-items:list",
  BillingPricingRuleItemsRead: "billing-pricing-rule-items:read",
  BillingPricingRuleItemsCreate: "billing-pricing-rule-items:create",
  BillingPricingRuleItemsUpdate: "billing-pricing-rule-items:update",
  BillingPricingRuleItemsDelete: "billing-pricing-rule-items:delete",
  BillingPricingRuleItemsManage: "billing-pricing-rule-items:manage",

  BillingBillableEventPoliciesList: "billing-billable-event-policies:list",
  BillingBillableEventPoliciesRead: "billing-billable-event-policies:read",
  BillingBillableEventPoliciesCreate: "billing-billable-event-policies:create",
  BillingBillableEventPoliciesUpdate: "billing-billable-event-policies:update",
  BillingBillableEventPoliciesDelete: "billing-billable-event-policies:delete",
  BillingBillableEventPoliciesManage: "billing-billable-event-policies:manage",

  BillingWorkflowDecisionsList: "billing-workflow-decisions:list",
  BillingWorkflowDecisionsRead: "billing-workflow-decisions:read",
  BillingWorkflowDecisionsCreate: "billing-workflow-decisions:create",
  BillingWorkflowDecisionsUpdate: "billing-workflow-decisions:update",
  BillingWorkflowDecisionsDelete: "billing-workflow-decisions:delete",
  BillingWorkflowDecisionsManage: "billing-workflow-decisions:manage",

  TenantPaymentGatewayConfigsList: "tenant-payment-gateway-configs:list",
  TenantPaymentGatewayConfigsRead: "tenant-payment-gateway-configs:read",
  TenantPaymentGatewayConfigsCreate: "tenant-payment-gateway-configs:create",
  TenantPaymentGatewayConfigsUpdate: "tenant-payment-gateway-configs:update",
  TenantPaymentGatewayConfigsDelete: "tenant-payment-gateway-configs:delete",
  TenantPaymentGatewayConfigsManage: "tenant-payment-gateway-configs:manage",
  BillingGatewayConfigsList: "tenant-payment-gateway-configs:list",
  BillingGatewayConfigsCreate: "tenant-payment-gateway-configs:create",
  BillingGatewayConfigsUpdate: "tenant-payment-gateway-configs:update",
  BillingGatewayConfigsDelete: "tenant-payment-gateway-configs:delete",

  // Assessment & Results
  AssessmentList: "assessment:list",
  AssessmentRead: "assessment:read",
  AssessmentCreate: "assessment:create",
  AssessmentUpdate: "assessment:update",
  AssessmentDelete: "assessment:delete",
  AssessmentManage: "assessment:manage",

  ResultList: "result:list",
  ResultRead: "result:read",
  ResultCreate: "result:create",
  ResultUpdate: "result:update",
  ResultDelete: "result:delete",
  ResultManage: "result:manage",
  ResultBroadsheetRead: "result:read",
  ResultBroadsheetExport: "result:read",

  CohortBroadsheetApprovalsList: "cohort-broadsheet-approvals:list",
  CohortBroadsheetApprovalsRead: "cohort-broadsheet-approvals:read",
  CohortBroadsheetApprovalsCreate: "cohort-broadsheet-approvals:create",
  CohortBroadsheetApprovalsUpdate: "cohort-broadsheet-approvals:update",
  CohortBroadsheetApprovalsDelete: "cohort-broadsheet-approvals:delete",
  CohortBroadsheetApprovalsManage: "cohort-broadsheet-approvals:manage",

  // Academic Standings
  AcademicStandingsList: "academic-standings:list",
  AcademicStandingsRead: "academic-standings:read",
  AcademicStandingsCreate: "academic-standings:create",
  AcademicStandingsUpdate: "academic-standings:update",
  AcademicStandingsDelete: "academic-standings:delete",
  AcademicStandingsManage: "academic-standings:manage",

  AcademicStandingBoundariesList: "academic-standing-boundaries:list",
  AcademicStandingBoundariesRead: "academic-standing-boundaries:read",
  AcademicStandingBoundariesCreate: "academic-standing-boundaries:create",
  AcademicStandingBoundariesUpdate: "academic-standing-boundaries:update",
  AcademicStandingBoundariesDelete: "academic-standing-boundaries:delete",
  AcademicStandingBoundariesManage: "academic-standing-boundaries:manage",

  AcademicStandingDegreeClassificationsList: "academic-standing-degree-classifications:list",
  AcademicStandingDegreeClassificationsRead: "academic-standing-degree-classifications:read",
  AcademicStandingDegreeClassificationsCreate: "academic-standing-degree-classifications:create",
  AcademicStandingDegreeClassificationsUpdate: "academic-standing-degree-classifications:update",
  AcademicStandingDegreeClassificationsDelete: "academic-standing-degree-classifications:delete",
  AcademicStandingDegreeClassificationsManage: "academic-standing-degree-classifications:manage",

  AcademicStandingEscalationStepsList: "academic-standing-escalation-steps:list",
  AcademicStandingEscalationStepsRead: "academic-standing-escalation-steps:read",
  AcademicStandingEscalationStepsCreate: "academic-standing-escalation-steps:create",
  AcademicStandingEscalationStepsUpdate: "academic-standing-escalation-steps:update",
  AcademicStandingEscalationStepsDelete: "academic-standing-escalation-steps:delete",
  AcademicStandingEscalationStepsManage: "academic-standing-escalation-steps:manage",

  // User Management
  UsersList: "users:list",
  UsersRead: "users:read",
  UsersCreate: "users:create",
  UsersUpdate: "users:update",
  UsersDelete: "users:delete",
  UsersManage: "users:manage",

  RoleAssignableRolesList: "role-assignable-roles:list",
  RoleAssignableRolesRead: "role-assignable-roles:read",
  RoleAssignableRolesCreate: "role-assignable-roles:create",
  RoleAssignableRolesUpdate: "role-assignable-roles:update",
  RoleAssignableRolesDelete: "role-assignable-roles:delete",
  RoleAssignableRolesManage: "role-assignable-roles:manage",

  // Audit Logs & Course Allocations
  AuditLogsList: "audit-logs:list",
  AuditLogsRead: "audit-logs:read",
  AuditLogsCreate: "audit-logs:create",
  AuditLogsUpdate: "audit-logs:update",
  AuditLogsDelete: "audit-logs:delete",
  AuditLogsManage: "audit-logs:manage",

  CourseAllocationsList: "course-allocations:list",
  CourseAllocationsRead: "course-allocations:read",
  CourseAllocationsCreate: "course-allocations:create",
  CourseAllocationsUpdate: "course-allocations:update",
  CourseAllocationsDelete: "course-allocations:delete",
  CourseAllocationsManage: "course-allocations:manage",

  // Level Categories & Formats
  LevelCategoriesList: "level-categories:list",
  LevelCategoriesRead: "level-categories:read",
  LevelCategoriesCreate: "level-categories:create",
  LevelCategoriesUpdate: "level-categories:update",
  LevelCategoriesDelete: "level-categories:delete",
  LevelCategoriesManage: "level-categories:manage",

  MatricNumberFormatsList: "matric-number-formats:list",
  MatricNumberFormatsRead: "matric-number-formats:read",
  MatricNumberFormatsCreate: "matric-number-formats:create",
  MatricNumberFormatsUpdate: "matric-number-formats:update",
  MatricNumberFormatsDelete: "matric-number-formats:delete",
  MatricNumberFormatsManage: "matric-number-formats:manage",
  MatricNumberFormatsActivate: "matric-number-formats:manage",

  CohortProgressionLogsList: "cohort-progression-logs:list",
  CohortProgressionLogsRead: "cohort-progression-logs:read",
  CohortProgressionLogsCreate: "cohort-progression-logs:create",
  CohortProgressionLogsUpdate: "cohort-progression-logs:update",
  CohortProgressionLogsDelete: "cohort-progression-logs:delete",
  CohortProgressionLogsManage: "cohort-progression-logs:manage",

  DocumentSignatoriesList: "document-signatories:list",
  DocumentSignatoriesRead: "document-signatories:read",
  DocumentSignatoriesCreate: "document-signatories:create",
  DocumentSignatoriesUpdate: "document-signatories:update",
  DocumentSignatoriesDelete: "document-signatories:delete",
  DocumentSignatoriesManage: "document-signatories:manage",

  // Dashboard & Setup Checklist
  DashboardList: "dashboard:list",
  DashboardRead: "dashboard:read",
  DashboardCreate: "dashboard:create",
  DashboardUpdate: "dashboard:update",
  DashboardDelete: "dashboard:delete",
  DashboardManage: "dashboard:manage",

  SetupChecklistList: "setup-checklist:list",
  SetupChecklistRead: "setup-checklist:read",
  SetupChecklistCreate: "setup-checklist:create",
  SetupChecklistUpdate: "setup-checklist:update",
  SetupChecklistDelete: "setup-checklist:delete",
  SetupChecklistManage: "setup-checklist:manage",

  // Approval Workflows
  WorkflowDefinitionsList: "workflow-definitions:list",
  WorkflowDefinitionsRead: "workflow-definitions:read",
  WorkflowDefinitionsCreate: "workflow-definitions:create",
  WorkflowDefinitionsUpdate: "workflow-definitions:update",
  WorkflowDefinitionsDelete: "workflow-definitions:delete",
  WorkflowDefinitionsManage: "workflow-definitions:manage",

  WorkflowStepsList: "workflow-steps:list",
  WorkflowStepsRead: "workflow-steps:read",
  WorkflowStepsCreate: "workflow-steps:create",
  WorkflowStepsUpdate: "workflow-steps:update",
  WorkflowStepsDelete: "workflow-steps:delete",
  WorkflowStepsManage: "workflow-steps:manage",

  WorkflowTransitionsList: "workflow-transitions:list",
  WorkflowTransitionsRead: "workflow-transitions:read",
  WorkflowTransitionsCreate: "workflow-transitions:create",
  WorkflowTransitionsUpdate: "workflow-transitions:update",
  WorkflowTransitionsDelete: "workflow-transitions:delete",
  WorkflowTransitionsManage: "workflow-transitions:manage",

  WorkflowExecutionsList: "workflow-executions:list",
  WorkflowExecutionsRead: "workflow-executions:read",
  WorkflowExecutionsCreate: "workflow-executions:create",
  WorkflowExecutionsUpdate: "workflow-executions:update",
  WorkflowExecutionsDelete: "workflow-executions:delete",
  WorkflowExecutionsManage: "workflow-executions:manage",

  WorkflowAuditLogsList: "workflow-audit-logs:list",
  WorkflowAuditLogsRead: "workflow-audit-logs:read",
  WorkflowAuditLogsCreate: "workflow-audit-logs:create",
  WorkflowAuditLogsUpdate: "workflow-audit-logs:update",
  WorkflowAuditLogsDelete: "workflow-audit-logs:delete",
  WorkflowAuditLogsManage: "workflow-audit-logs:manage",
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];
