export const Permission = {
  // Faculties
  FacultiesList: "faculties:list",
  FacultiesRead: "faculties:read",
  FacultiesCreate: "faculties:create",
  FacultiesUpdate: "faculties:update",
  FacultiesDelete: "faculties:delete",
  FacultiesManage: "faculties:manage",
  // Departments
  DepartmentsList: "departments:list",
  DepartmentsRead: "departments:read",
  DepartmentsCreate: "departments:create",
  DepartmentsUpdate: "departments:update",
  DepartmentsDelete: "departments:delete",
  DepartmentsManage: "departments:manage",
  // Programs
  ProgramsList: "programs:list",
  ProgramsRead: "programs:read",
  ProgramsCreate: "programs:create",
  ProgramsUpdate: "programs:update",
  ProgramsDelete: "programs:delete",
  ProgramsManage: "programs:manage",
  // Graduation Requirements
  GraduationRequirementsList: "graduation-requirements:list",
  GraduationRequirementsRead: "graduation-requirements:read",
  GraduationRequirementsCreate: "graduation-requirements:create",
  GraduationRequirementsUpdate: "graduation-requirements:update",
  GraduationRequirementsDelete: "graduation-requirements:delete",
  GraduationRequirementsManage: "graduation-requirements:manage",
  // Courses
  CoursesList: "courses:list",
  CoursesRead: "courses:read",
  CoursesCreate: "courses:create",
  CoursesUpdate: "courses:update",
  CoursesDelete: "courses:delete",
  CoursesManage: "courses:manage",
  // Course Configurations
  CourseConfigsList: "course-configurations:list",
  CourseConfigsRead: "course-configurations:read",
  CourseConfigsCreate: "course-configurations:create",
  CourseConfigsUpdate: "course-configurations:update",
  CourseConfigsDelete: "course-configurations:delete",
  CourseConfigsManage: "course-configurations:manage",
  // Curriculum Versions
  CurriculumVersionsList: "curriculum-versions:list",
  CurriculumVersionsRead: "curriculum-versions:read",
  CurriculumVersionsCreate: "curriculum-versions:create",
  CurriculumVersionsUpdate: "curriculum-versions:update",
  CurriculumVersionsDelete: "curriculum-versions:delete",
  CurriculumVersionsManage: "curriculum-versions:manage",
  // Academic Sessions
  AcademicSessionsList: "academic-sessions:list",
  AcademicSessionsRead: "academic-sessions:read",
  AcademicSessionsCreate: "academic-sessions:create",
  AcademicSessionsUpdate: "academic-sessions:update",
  AcademicSessionsDelete: "academic-sessions:delete",
  AcademicSessionsManage: "academic-sessions:manage",
  // Semesters
  SemestersList: "semesters:list",
  SemestersRead: "semesters:read",
  SemestersCreate: "semesters:create",
  SemestersUpdate: "semesters:update",
  SemestersDelete: "semesters:delete",
  SemestersManage: "semesters:manage",
  // Semester Types
  SemesterTypesList: "semester-types:list",
  SemesterTypesRead: "semester-types:read",
  SemesterTypesCreate: "semester-types:create",
  SemesterTypesUpdate: "semester-types:update",
  SemesterTypesDelete: "semester-types:delete",
  SemesterTypesManage: "semester-types:manage",
  // Levels
  LevelsList: "levels:list",
  LevelsRead: "levels:read",
  LevelsCreate: "levels:create",
  LevelsUpdate: "levels:update",
  LevelsDelete: "levels:delete",
  LevelsManage: "levels:manage",
  // Students
  StudentsList: "students:list",
  StudentsRead: "students:read",
  StudentsCreate: "students:create",
  StudentsUpdate: "students:update",
  StudentsDelete: "students:delete",
  StudentsManage: "students:manage",
  // Student Enrollment Transitions
  StudentEnrollmentTransitionsList: "student-enrollment-transitions:list",
  StudentEnrollmentTransitionsRead: "student-enrollment-transitions:read",
  StudentEnrollmentTransitionsCreate: "student-enrollment-transitions:create",
  StudentEnrollmentTransitionsUpdate: "student-enrollment-transitions:update",
  StudentEnrollmentTransitionsDelete: "student-enrollment-transitions:delete",
  StudentEnrollmentTransitionsManage: "student-enrollment-transitions:manage",
  // Student Course Registrations
  StudentCourseRegistrationsList: "student-course-registrations:list",
  StudentCourseRegistrationsRead: "student-course-registrations:read",
  StudentCourseRegistrationsCreate: "student-course-registrations:create",
  StudentCourseRegistrationsUpdate: "student-course-registrations:update",
  StudentCourseRegistrationsDelete: "student-course-registrations:delete",
  StudentCourseRegistrationsManage: "student-course-registrations:manage",
  // Student Score Sheets
  StudentScoreSheetsList: "student-score-sheets:list",
  StudentScoreSheetsRead: "student-score-sheets:read",
  StudentScoreSheetsCreate: "student-score-sheets:create",
  StudentScoreSheetsUpdate: "student-score-sheets:update",
  StudentScoreSheetsDelete: "student-score-sheets:delete",
  StudentScoreSheetsManage: "student-score-sheets:manage",
  // Student Transition Statuses
  StudentTransitionStatusesList: "student-transition-statuses:list",
  StudentTransitionStatusesRead: "student-transition-statuses:read",
  StudentTransitionStatusesCreate: "student-transition-statuses:create",
  StudentTransitionStatusesUpdate: "student-transition-statuses:update",
  StudentTransitionStatusesDelete: "student-transition-statuses:delete",
  StudentTransitionStatusesManage: "student-transition-statuses:manage",
  // Staff
  StaffList: "staff:list",
  StaffRead: "staff:read",
  StaffCreate: "staff:create",
  StaffUpdate: "staff:update",
  StaffDelete: "staff:delete",
  StaffManage: "staff:manage",
  // Roles
  RolesList: "roles:list",
  RolesRead: "roles:read",
  RolesCreate: "roles:create",
  RolesUpdate: "roles:update",
  RolesDelete: "roles:delete",
  RolesManage: "roles:manage",
  // Permissions
  PermissionsList: "permissions:list",
  PermissionsRead: "permissions:read",
  PermissionsCreate: "permissions:create",
  PermissionsUpdate: "permissions:update",
  PermissionsDelete: "permissions:delete",
  PermissionsManage: "permissions:manage",
  // User Roles
  UserRolesList: "user-roles:list",
  UserRolesRead: "user-roles:read",
  UserRolesCreate: "user-roles:create",
  UserRolesUpdate: "user-roles:update",
  UserRolesDelete: "user-roles:delete",
  UserRolesManage: "user-roles:manage",
  // System Configs
  SystemConfigsList: "system-configs:list",
  SystemConfigsRead: "system-configs:read",
  SystemConfigsCreate: "system-configs:create",
  SystemConfigsUpdate: "system-configs:update",
  SystemConfigsDelete: "system-configs:delete",
  SystemConfigsManage: "system-configs:manage",
  // Registration Credit Limits
  RegistrationCreditLimitsList: "programs:list",
  RegistrationCreditLimitsRead: "programs:read",
  RegistrationCreditLimitsCreate: "programs:create",
  RegistrationCreditLimitsUpdate: "programs:update",
  RegistrationCreditLimitsDelete: "programs:delete",
  RegistrationCreditLimitsManage: "programs:manage",
  // Brand Configs
  BrandConfigsList: "brand-configs:list",
  BrandConfigsRead: "brand-configs:read",
  BrandConfigsCreate: "brand-configs:create",
  BrandConfigsUpdate: "brand-configs:update",
  BrandConfigsDelete: "brand-configs:delete",
  BrandConfigsManage: "brand-configs:manage",
  // Grading Schema Configs
  GradingSchemaConfigsList: "grading-schema-configs:list",
  GradingSchemaConfigsRead: "grading-schema-configs:read",
  GradingSchemaConfigsCreate: "grading-schema-configs:create",
  GradingSchemaConfigsUpdate: "grading-schema-configs:update",
  GradingSchemaConfigsDelete: "grading-schema-configs:delete",
  GradingSchemaConfigsManage: "grading-schema-configs:manage",
  // Grading
  GradingList: "grading:list",
  GradingRead: "grading:read",
  GradingCreate: "grading:create",
  GradingUpdate: "grading:update",
  GradingDelete: "grading:delete",
  GradingManage: "grading:manage",
  // Score Evaluation Statuses
  ScoreEvaluationStatusesList: "grading:list",
  ScoreEvaluationStatusesCreate: "grading:create",
  ScoreEvaluationStatusesUpdate: "grading:update",
  ScoreEvaluationStatusesDelete: "grading:delete",

  // ScoreEvaluationStatusesList: "score-evaluation-statuses:list",
  // ScoreEvaluationStatusesCreate: "score-evaluation-statuses:create",
  // ScoreEvaluationStatusesUpdate: "score-evaluation-statuses:update",
  // ScoreEvaluationStatusesDelete: "score-evaluation-statuses:delete",

  // System Time Frames
  SystemTimeFramesList: "grading:list",
  SystemTimeFramesRead: "grading:read",
  SystemTimeFramesCreate: "grading:create",
  SystemTimeFramesUpdate: "grading:update",
  SystemTimeFramesDelete: "grading:delete",
  SystemTimeFramesManage: "grading:manage",

  // SystemTimeFramesList:   'system-time-frames:list',
  // SystemTimeFramesRead:   'system-time-frames:read',
  // SystemTimeFramesCreate: 'system-time-frames:create',
  // SystemTimeFramesUpdate: 'system-time-frames:update',
  // SystemTimeFramesDelete: 'system-time-frames:delete',
  // SystemTimeFramesManage: 'system-time-frames:manage',

  // Course Assessment Policies
  CourseAssessmentPoliciesList: "course-configurations:list",
  CourseAssessmentPoliciesRead: "course-configurations:read",
  CourseAssessmentPoliciesCreate: "course-configurations:create",
  CourseAssessmentPoliciesUpdate: "course-configurations:update",
  CourseAssessmentPoliciesDelete: "course-configurations:delete",
  // Course Assessment Components
  CourseAssessmentComponentsList: "course-configurations:list",
  CourseAssessmentComponentsCreate: "course-configurations:create",
  CourseAssessmentComponentsUpdate: "course-configurations:update",
  CourseAssessmentComponentsDelete: "course-configurations:delete",
  // Admission Scoring Strategies
  AdmissionScoringStrategiesList: "system-configs:list",
  AdmissionScoringStrategiesCreate: "system-configs:create",
  AdmissionScoringStrategiesUpdate: "system-configs:update",
  AdmissionScoringStrategiesDelete: "system-configs:delete",
  AdmissionScoringStrategiesManage: "system-configs:manage",
  // Admission Program Config (Cut-offs / Quota)
  AdmissionProgramAdmissionConfigsList: "system-configs:list",
  AdmissionProgramAdmissionConfigsCreate: "system-configs:create",
  AdmissionProgramAdmissionConfigsUpdate: "system-configs:update",
  AdmissionProgramAdmissionConfigsDelete: "system-configs:delete",
  AdmissionProgramAdmissionConfigsManage: "system-configs:manage",
  // Admission Cycles
  AdmissionCyclesList: "system-configs:list",
  AdmissionCyclesCreate: "system-configs:create",
  AdmissionCyclesUpdate: "system-configs:update",
  AdmissionCyclesDelete: "system-configs:delete",
  AdmissionCyclesTransition: "system-configs:manage",
  // Admission Geography Rules
  AdmissionGeographyRulesList: "system-configs:list",
  AdmissionGeographyRulesCreate: "system-configs:create",
  AdmissionGeographyRulesUpdate: "system-configs:update",
  AdmissionGeographyRulesDelete: "system-configs:delete",
  // Admission O-Level Subjects
  AdmissionOlevelSubjectsList: "system-configs:list",
  AdmissionOlevelSubjectsCreate: "system-configs:create",
  AdmissionOlevelSubjectsUpdate: "system-configs:update",
  AdmissionOlevelSubjectsDelete: "system-configs:delete",
  AdmissionOlevelSubjectsManage: "system-configs:manage",
  // Admission O-Level Grade Points
  AdmissionOlevelGradePointsList: "system-configs:list",
  AdmissionOlevelGradePointsCreate: "system-configs:create",
  AdmissionOlevelGradePointsUpdate: "system-configs:update",
  AdmissionOlevelGradePointsDelete: "system-configs:delete",
  // Admission Program O'Level Requirements
  AdmissionProgramOlevelRulesList: "system-configs:list",
  AdmissionProgramOlevelRulesCreate: "system-configs:create",
  AdmissionProgramOlevelRulesUpdate: "system-configs:update",
  AdmissionProgramOlevelRulesDelete: "system-configs:delete",
  // Admission JAMB Rules
  AdmissionJambRulesList: "system-configs:list",
  AdmissionJambRulesCreate: "system-configs:create",
  AdmissionJambRulesUpdate: "system-configs:update",
  AdmissionJambRulesDelete: "system-configs:delete",
  AdmissionJambRulesManage: "system-configs:manage",
  // Admission Candidates
  AdmissionCandidatesList: "system-configs:list",
  AdmissionCandidatesCreate: "system-configs:create",
  AdmissionCandidatesUpdate: "system-configs:update",
  AdmissionCandidatesManage: "system-configs:manage",
  // Billing Billable Events
  // BillingBillableEventsList: "billing-billable-events:list",
  // BillingBillableEventsCreate: "billing-billable-events:create",
  // BillingBillableEventsUpdate: "billing-billable-events:update",
  // BillingBillableEventsDelete: "billing-billable-events:delete",

  BillingBillableEventsList: "system-configs:list",
  BillingBillableEventsCreate: "system-configs:create",
  BillingBillableEventsUpdate: "system-configs:update",
  BillingBillableEventsDelete: "system-configs:delete",
  // Billing Fee Items
  // BillingFeeItemsList: "billing-fee-items:list",
  // BillingFeeItemsCreate: "billing-fee-items:create",
  // BillingFeeItemsUpdate: "billing-fee-items:update",
  // BillingFeeItemsDelete: "billing-fee-items:delete",
  BillingFeeItemsList: "system-configs:list",
  BillingFeeItemsCreate: "system-configs:create",
  BillingFeeItemsUpdate: "system-configs:update",
  BillingFeeItemsDelete: "system-configs:delete",
  // Billing Pricing Rules
  // BillingPricingRulesList: "billing-pricing-rules:list",
  // BillingPricingRulesCreate: "billing-pricing-rules:create",
  // BillingPricingRulesUpdate: "billing-pricing-rules:update",
  // BillingPricingRulesDelete: "billing-pricing-rules:delete",
  BillingPricingRulesList: "system-configs:list",
  BillingPricingRulesCreate: "system-configs:create",
  BillingPricingRulesUpdate: "system-configs:update",
  BillingPricingRulesDelete: "system-configs:delete",
  // Billing finance read (wire to catalogue when available)
  // BillingInvoicesList: "billing-invoices:list",
  // BillingPaymentsList: "billing-payments:list",
  // BillingPaymentTransactionsList: "billing-payment-transactions:list",
  BillingInvoicesList: "system-configs:list",
  BillingPaymentsList: "system-configs:list",
  BillingPaymentTransactionsList: "system-configs:list",
  // Billing Payment Gateway Configs
  // BillingGatewayConfigsList: "billing-gateway-configs:list",
  // BillingGatewayConfigsCreate: "billing-gateway-configs:create",
  // BillingGatewayConfigsUpdate: "billing-gateway-configs:update",
  // BillingGatewayConfigsDelete: "billing-gateway-configs:delete",
  BillingGatewayConfigsList: "system-configs:list",
  BillingGatewayConfigsCreate: "system-configs:create",
  BillingGatewayConfigsUpdate: "system-configs:update",
  BillingGatewayConfigsDelete: "system-configs:delete",
  // Dynamic Forms
  DynamicFormsList: "dynamic-forms:list",
  DynamicFormsRead: "dynamic-forms:read",
  DynamicFormsCreate: "dynamic-forms:create",
  DynamicFormsUpdate: "dynamic-forms:update",
  DynamicFormsDelete: "dynamic-forms:delete",
  DynamicFormsManage: "dynamic-forms:manage",
  // Dynamic Form Assignments
  DynamicFormAssignmentsList: "dynamic-form-assignments:list",
  DynamicFormAssignmentsRead: "dynamic-form-assignments:read",
  DynamicFormAssignmentsCreate: "dynamic-form-assignments:create",
  DynamicFormAssignmentsUpdate: "dynamic-form-assignments:update",
  DynamicFormAssignmentsDelete: "dynamic-form-assignments:delete",
  DynamicFormAssignmentsManage: "dynamic-form-assignments:manage",
  // Dynamic Form Submissions
  DynamicFormSubmissionsList: "dynamic-form-submissions:list",
  DynamicFormSubmissionsRead: "dynamic-form-submissions:read",

  AdmissionRecommendedCandidatesList: "admission-recommended-candidates:list",

  // Admission Document Types
  AdmissionDocumentTypesList: "system-configs:list",
  AdmissionDocumentTypesCreate: "system-configs:create",
  AdmissionDocumentTypesUpdate: "system-configs:update",
  AdmissionDocumentTypesDelete: "system-configs:delete",
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];
