export const Permission = {
  // Faculties
  FacultiesList: "faculties:list",
  FacultiesRead: "faculties:read",
  FacultiesCreate: "faculties:create",
  FacultiesUpdate: "faculties:update",
  FacultiesDelete: "faculties:delete",
  FacultiesManage: "faculties:manage",
  // Departments
  DepartmentsList: "departments:list",
  DepartmentsRead: "departments:read",
  DepartmentsCreate: "departments:create",
  DepartmentsUpdate: "departments:update",
  DepartmentsDelete: "departments:delete",
  DepartmentsManage: "departments:manage",
  // Programs
  ProgramsList: "programs:list",
  ProgramsRead: "programs:read",
  ProgramsCreate: "programs:create",
  ProgramsUpdate: "programs:update",
  ProgramsDelete: "programs:delete",
  ProgramsManage: "programs:manage",
  // Graduation Requirements
  GraduationRequirementsList: "graduation-requirements:list",
  GraduationRequirementsRead: "graduation-requirements:read",
  GraduationRequirementsCreate: "graduation-requirements:create",
  GraduationRequirementsUpdate: "graduation-requirements:update",
  GraduationRequirementsDelete: "graduation-requirements:delete",
  GraduationRequirementsManage: "graduation-requirements:manage",
  // Courses
  CoursesList: "courses:list",
  CoursesRead: "courses:read",
  CoursesCreate: "courses:create",
  CoursesUpdate: "courses:update",
  CoursesDelete: "courses:delete",
  CoursesManage: "courses:manage",
  // Course Configurations
  CourseConfigsList: "course-configurations:list",
  CourseConfigsRead: "course-configurations:read",
  CourseConfigsCreate: "course-configurations:create",
  CourseConfigsUpdate: "course-configurations:update",
  CourseConfigsDelete: "course-configurations:delete",
  CourseConfigsManage: "course-configurations:manage",
  // Curriculum Versions
  CurriculumVersionsList: "curriculum-versions:list",
  CurriculumVersionsRead: "curriculum-versions:read",
  CurriculumVersionsCreate: "curriculum-versions:create",
  CurriculumVersionsUpdate: "curriculum-versions:update",
  CurriculumVersionsDelete: "curriculum-versions:delete",
  CurriculumVersionsManage: "curriculum-versions:manage",
  // Academic Sessions
  AcademicSessionsList: "academic-sessions:list",
  AcademicSessionsRead: "academic-sessions:read",
  AcademicSessionsCreate: "academic-sessions:create",
  AcademicSessionsUpdate: "academic-sessions:update",
  AcademicSessionsDelete: "academic-sessions:delete",
  AcademicSessionsManage: "academic-sessions:manage",
  // Semesters
  SemestersList: "semesters:list",
  SemestersRead: "semesters:read",
  SemestersCreate: "semesters:create",
  SemestersUpdate: "semesters:update",
  SemestersDelete: "semesters:delete",
  SemestersManage: "semesters:manage",
  // Semester Types
  SemesterTypesList: "semester-types:list",
  SemesterTypesRead: "semester-types:read",
  SemesterTypesCreate: "semester-types:create",
  SemesterTypesUpdate: "semester-types:update",
  SemesterTypesDelete: "semester-types:delete",
  SemesterTypesManage: "semester-types:manage",
  // Levels
  LevelsList: "levels:list",
  LevelsRead: "levels:read",
  LevelsCreate: "levels:create",
  LevelsUpdate: "levels:update",
  LevelsDelete: "levels:delete",
  LevelsManage: "levels:manage",
  // Students
  StudentsList: "students:list",
  StudentsRead: "students:read",
  StudentsCreate: "students:create",
  StudentsUpdate: "students:update",
  StudentsDelete: "students:delete",
  StudentsManage: "students:manage",
  // Student Enrollment Transitions
  StudentEnrollmentTransitionsList: "student-enrollment-transitions:list",
  StudentEnrollmentTransitionsRead: "student-enrollment-transitions:read",
  StudentEnrollmentTransitionsCreate: "student-enrollment-transitions:create",
  StudentEnrollmentTransitionsUpdate: "student-enrollment-transitions:update",
  StudentEnrollmentTransitionsDelete: "student-enrollment-transitions:delete",
  StudentEnrollmentTransitionsManage: "student-enrollment-transitions:manage",
  // Student Course Registrations
  StudentCourseRegistrationsList: "student-course-registrations:list",
  StudentCourseRegistrationsRead: "student-course-registrations:read",
  StudentCourseRegistrationsCreate: "student-course-registrations:create",
  StudentCourseRegistrationsUpdate: "student-course-registrations:update",
  StudentCourseRegistrationsDelete: "student-course-registrations:delete",
  StudentCourseRegistrationsManage: "student-course-registrations:manage",
  // Student Score Sheets
  StudentScoreSheetsList: "student-score-sheets:list",
  StudentScoreSheetsRead: "student-score-sheets:read",
  StudentScoreSheetsCreate: "student-score-sheets:create",
  StudentScoreSheetsUpdate: "student-score-sheets:update",
  StudentScoreSheetsDelete: "student-score-sheets:delete",
  StudentScoreSheetsManage: "student-score-sheets:manage",
  // Student Transition Statuses
  StudentTransitionStatusesList: "student-transition-statuses:list",
  StudentTransitionStatusesRead: "student-transition-statuses:read",
  StudentTransitionStatusesCreate: "student-transition-statuses:create",
  StudentTransitionStatusesUpdate: "student-transition-statuses:update",
  StudentTransitionStatusesDelete: "student-transition-statuses:delete",
  StudentTransitionStatusesManage: "student-transition-statuses:manage",
  // Staff
  StaffList: "staff:list",
  StaffRead: "staff:read",
  StaffCreate: "staff:create",
  StaffUpdate: "staff:update",
  StaffDelete: "staff:delete",
  StaffManage: "staff:manage",
  // Roles
  RolesList: "roles:list",
  RolesRead: "roles:read",
  RolesCreate: "roles:create",
  RolesUpdate: "roles:update",
  RolesDelete: "roles:delete",
  RolesManage: "roles:manage",
  // Permissions
  PermissionsList: "permissions:list",
  PermissionsRead: "permissions:read",
  PermissionsCreate: "permissions:create",
  PermissionsUpdate: "permissions:update",
  PermissionsDelete: "permissions:delete",
  PermissionsManage: "permissions:manage",
  // User Roles
  UserRolesList: "user-roles:list",
  UserRolesRead: "user-roles:read",
  UserRolesCreate: "user-roles:create",
  UserRolesUpdate: "user-roles:update",
  UserRolesDelete: "user-roles:delete",
  UserRolesManage: "user-roles:manage",
  // System Configs
  SystemConfigsList: "system-configs:list",
  SystemConfigsRead: "system-configs:read",
  SystemConfigsCreate: "system-configs:create",
  SystemConfigsUpdate: "system-configs:update",
  SystemConfigsDelete: "system-configs:delete",
  SystemConfigsManage: "system-configs:manage",
  // Registration Credit Limits
  RegistrationCreditLimitsList: "programs:list",
  RegistrationCreditLimitsRead: "programs:read",
  RegistrationCreditLimitsCreate: "programs:create",
  RegistrationCreditLimitsUpdate: "programs:update",
  RegistrationCreditLimitsDelete: "programs:delete",
  RegistrationCreditLimitsManage: "programs:manage",
  // Brand Configs
  BrandConfigsList: "brand-configs:list",
  BrandConfigsRead: "brand-configs:read",
  BrandConfigsCreate: "brand-configs:create",
  BrandConfigsUpdate: "brand-configs:update",
  BrandConfigsDelete: "brand-configs:delete",
  BrandConfigsManage: "brand-configs:manage",
  // Grading Schema Configs
  GradingSchemaConfigsList: "grading-schema-configs:list",
  GradingSchemaConfigsRead: "grading-schema-configs:read",
  GradingSchemaConfigsCreate: "grading-schema-configs:create",
  GradingSchemaConfigsUpdate: "grading-schema-configs:update",
  GradingSchemaConfigsDelete: "grading-schema-configs:delete",
  GradingSchemaConfigsManage: "grading-schema-configs:manage",
  // Grading
  GradingList: "grading:list",
  GradingRead: "grading:read",
  GradingCreate: "grading:create",
  GradingUpdate: "grading:update",
  GradingDelete: "grading:delete",
  GradingManage: "grading:manage",
  // System Time Frames
  SystemTimeFramesList: "grading:list",
  SystemTimeFramesRead: "grading:read",
  SystemTimeFramesCreate: "grading:create",
  SystemTimeFramesUpdate: "grading:update",
  SystemTimeFramesDelete: "grading:delete",
  SystemTimeFramesManage: "grading:manage",

  // SystemTimeFramesList:   'system-time-frames:list',
  // SystemTimeFramesRead:   'system-time-frames:read',
  // SystemTimeFramesCreate: 'system-time-frames:create',
  // SystemTimeFramesUpdate: 'system-time-frames:update',
  // SystemTimeFramesDelete: 'system-time-frames:delete',
  // SystemTimeFramesManage: 'system-time-frames:manage',

  // Course Assessment Policies
  CourseAssessmentPoliciesList: "course-configurations:list",
  CourseAssessmentPoliciesRead: "course-configurations:read",
  CourseAssessmentPoliciesCreate: "course-configurations:create",
  CourseAssessmentPoliciesUpdate: "course-configurations:update",
  CourseAssessmentPoliciesDelete: "course-configurations:delete",
  // Course Assessment Components
  CourseAssessmentComponentsList: "course-configurations:list",
  CourseAssessmentComponentsCreate: "course-configurations:create",
  CourseAssessmentComponentsUpdate: "course-configurations:update",
  CourseAssessmentComponentsDelete: "course-configurations:delete",
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];
